<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');
class Motor_pagos_ejemplo extends CI_Controller {
  function __construct() {
		parent:: __construct();
    $this->load->library('Motorpago');
    $this->load->helper('form');
  }

  public function index(){

    

  }   public function get_movimientos()  {//METODO PARA OBTENER LOS MOVIMIENTOS BANCARIOS DE UNA ORDEN DE PAGO//PARAMETRO DE ENVÍO: referencia de orden de pago//PARAMETRO DE RETORNO: arreglo que contiene todas las columnas proporcionados por el banco respecto a las operaciones hechas en linea, cuando banco_respuesta_codigoerror es igual '0' quiere decir que la operación fue realizada exitosamente	  $resultado=$this->motorpago->obten_movimientos_banco('2018-ORT-1538410232');		var_dump($resultado);	    }public function get_subtotales(){//METODO PARA OBTENER SUBTOTALES DE UNA CLAVE DE INGRESO //PARAMETRO DE ENVÍO: id_clave_ingreso,cantidad//PARAMETRO DE RETORNO: arreglo con el total cálculado de esa clave de ingreso , cantidad, y monto divido por el monto a cobrar y su ajuste tarifario$resultado=$this->motorpago->get_total_clave_ingreso('152','3');var_dump($resultado);}
public function get_detalles_referencia(){//METODO PARA OBTENER LOS DETALLES DE UNA ORDEN DE PAGO //PARAMETRO DE ENVIO: referencia de la orden de pago//PARAMETRO DE RETORNO: arreglo con los detalles de la orden de pago, el parametro orden_pago_estatus indica si la orden de pago puede ser cobrada o no, cuando está en 0 significa que puede ser cobrada$resultado=$this->motorpago->get_detalles_referencia('2019-ORT-0000000004');var_dump($resultado);	}public function get_referencia(){//METODO PARA OBTENER UNA REFERENCIA DE ORDEN DE PAGO //PARAMETROS DE ENVÍO//dependencia_id= es el id de dependencia que proporciona tecnologías de la información//persona_id= se obtiene del campo persona_id del sistema único de usuarios, este campo solo se usa cuando el tipo de usuario es persona//empresa_id= se obtiene del campo empresa_id del sistema único de usuarios, este campo solo se usa cuando el tipo de usuarios es empresa//usuario_id= es el id del usuario logeado en el sistema, se obtiene del sistema único de usuarios//detalles=es un arreglo de varios conceptos que pueden ser agregados a la órden de pago//persona_id|empresa_id|id_clave_ingreso|cantidad ,  persona_id o empresa_id según el tipo de usuario logeado alguno de los 2 se manda como nulo, es el mismo dato que se mandó anteriormente, id clave de ingreso es la clave de ingreso del concepto a agregar, cantidad es la cantidad por la cual se multiplicara cada valor de la clave de ingreso//PARAMETRO DE RETORNO: arreglo con los detalles de la orden de pago generada, el campo referencia es el que se utilizara para posteriomente llamar el motor de pago$arreglo_detalles=array();//este renglon del arreglo de detalles es para cuando son claves de ingreso que tienen montos y se calcula todo el monto en el servidor$arreglo_detalles[0]="32|null|152|1";//PARA EL CASO DE CLAVES DE INGRESO ESPECIALES DONDE NO SE NECESITA UN CALCULO AUTOMATICO ESTA ES LA ESTRUCTURA//persona_id|empresa_id|clave_ingreso_id|cantidad|importe|importe_descuento|recargos|recargos_descuento|rezago|honorarios|ajuste_tarifario|monto|fecha_inicial|fecha_limite|cuenta_predial_id|anyo|bimestre|custom_data//los montos individuales y los ajustes tarifarios se calculan del lado del cliente y se envían en el arreglo$arreglo_detalles[1]="32|null|195|1|3954.42|null|null|null|null|null|0.42|3954.00|null|null|null|null|null|custom_data";$dependencia_id=4;$persona_id=32;$usuario_id=5;//la fecha límite es obligatoria en formato yyyy/mm/dd ya que es la vigencia de la órden de pago$fecha_limite="2018/12/12";//cuando enviamos arreglos con claves de ingreso especiales hay que enviar el parametro custom data en true$custom_data=TRUE;$resultado=$this->motorpago->get_referencia($dependencia_id,$persona_id,null,$usuario_id,$arreglo_detalles,$fecha_limite,$custom_data);var_dump($resultado);	}
public function get_motorpago(){//METODO PARA LLAMAR EL MOTOR DE PAGO//PARAMETRO DE ENVIO: referencia de la orden de pago,url_response_ok es la url a redireccionarse cuando el pago sea exitoso,url_response_ko es la url a redireccionarse cuando el pago no sea exitoso, el último parametro es el de control de prueba, cuando se pone en 0 se conecta directamente al motor de bancomer, cuando está en 1 se conecta al motor de pruebas del municipio, recomendamos en etapa de desarrollo manejar siempre en 1 el parametro//PARAMETRO DE RETORNO: el metodo no retorna datos, redirecciona a las urls indicadas$referencia="2019-ORT-0000000004";$url_response_ok="http://localhost/prueba/pruebamotor/respuesta_bancomer_ok";$url_response_ko="http://localhost/prueba/pruebamotor/respuesta_bancomer_ko";$this->motorpago->procesa_pago($referencia,$url_response_ok,$url_response_ko,1);		}

}
?>
